# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-12 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pothole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolylineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(blank=True, max_length=30)),
                ('score', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
