# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-10-12 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pothole', '0002_polylinedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polylinedata',
            old_name='filepath',
            new_name='filename',
        ),
    ]
